// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview This file defines a Genkit flow that generates descriptive statistics for election data.
 *
 * The flow takes election data as input and returns a set of descriptive statistics.
 * @fileOverview
 * - generateDescriptiveStatistics - A function that generates descriptive statistics for election data.
 * - GenerateDescriptiveStatisticsInput - The input type for the generateDescriptiveStatistics function.
 * - GenerateDescriptiveStatisticsOutput - The return type for the generateDescriptiveStatistics function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDescriptiveStatisticsInputSchema = z.object({
  electionData: z.string().describe('The election data in CSV format.'),
});

export type GenerateDescriptiveStatisticsInput = z.infer<
  typeof GenerateDescriptiveStatisticsInputSchema
>;

const GenerateDescriptiveStatisticsOutputSchema = z.object({
  statistics: z
    .string()
    .describe(
      'A JSON string containing descriptive statistics for the election data, including mean, median, mode, standard deviation, min, and max for relevant columns.'
    ),
});

export type GenerateDescriptiveStatisticsOutput = z.infer<
  typeof GenerateDescriptiveStatisticsOutputSchema
>;

export async function generateDescriptiveStatistics(
  input: GenerateDescriptiveStatisticsInput
): Promise<GenerateDescriptiveStatisticsOutput> {
  return generateDescriptiveStatisticsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateDescriptiveStatisticsPrompt',
  input: {schema: GenerateDescriptiveStatisticsInputSchema},
  output: {schema: GenerateDescriptiveStatisticsOutputSchema},
  prompt: `You are an expert data analyst specializing in election data.
  You will receive election data in CSV format.  Your goal is to generate descriptive statistics for the data, including mean, median, mode, standard deviation, min, and max for relevant columns.
  Return the statistics as a JSON string.

  Election Data: {{{electionData}}}
  `,
});

const generateDescriptiveStatisticsFlow = ai.defineFlow(
  {
    name: 'generateDescriptiveStatisticsFlow',
    inputSchema: GenerateDescriptiveStatisticsInputSchema,
    outputSchema: GenerateDescriptiveStatisticsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
